application: mylibrary-1205
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /books.php
  script: books.php

- url: /authors.php
  script: authors.php

- url: /collections.php
  script: collections.php

- url: /functions.php
  script: functions.php

- url: /header.php
  script: header.php

- url: /footer.php
  script: footer.php

- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /updateAuthors.php
  script: updateAuthors.php

- url: /updateBooks.php
  script: updateBooks.php

- url: /updateCollections.php
  script: updateCollections.php